### ISSUE TITLE
Doubt: Adding Commands to a Git Hook

### ISSUE THREAD

**Issue by btd1337** [xuzhongpeng/git_hooks#1]
How can I add the following commands to a pre-push?

- flutter analyze
- flutter test

As it is done here: https://medium.com/@MiBLT/improving-your-flutter-code-7424b10dc16a

**Comment by xuzhongpeng** [comment]
> How can I add the following commands to a pre-push?
> 
> * flutter analyze
> * flutter test
> 
> As it is done here: https://medium.com/@MiBLT/improving-your-flutter-code-7424b10dc16a

if you want implement this function in my package,you can do like this:

git_hooks.dart
```
import "package:git_hooks/git_hooks.dart";
import "dart:io";
void main(List arguments) {
  Map<Git, UserBackFun> params = {
    Git.prePush: prePush
  };
  change(arguments, params);
}

Future<bool> prePush() async {
  try{
  ProcessResult result = await Process.run(
        'flutter', ['analyze']);
  //...some judge depend result
  } catch (e) {
    print(e);
    return false;
  }
  return true;
}
```

**Comment by btd1337** [comment]
@xuzhongpeng I'm a little confused on some points. Would you mind converting this hook to your project format or putting some more complete examples in the documentation? Thanks in advance!

```
#!/bin/sh
# To use add to `.git/hooks/`
# Should be named `pre-push`
# Make executable with `chmod +x`

# stash any unstaged changes
git stash -q --keep-index

# run Flutter analyze + test
flutter analyze

if [ $? -ne 0 ]; then
        # unstash the unstashed changes
        git stash pop -q
        exit 1
fi

flutter test


if [ $? -ne 0 ]; then
        # unstash the unstashed changes
        git stash pop -q
        exit 1
fi

# unstash the unstashed changes
git stash pop -q
exit 0
```

**Comment by xuzhongpeng** [comment]
> @xuzhongpeng I'm a little confused on some points. Would you mind converting this hook to your project format or putting some more complete examples in the documentation? Thanks in advance!
> 
> ```
> #!/bin/sh
> # To use add to `.git/hooks/`
> # Should be named `pre-push`
> # Make executable with `chmod +x`
> 
> # stash any unstaged changes
> git stash -q --keep-index
> 
> # run Flutter analyze + test
> flutter analyze
> 
> if [ $? -ne 0 ]; then
>         # unstash the unstashed changes
>         git stash pop -q
>         exit 1
> fi
> 
> flutter test
> 
> 
> if [ $? -ne 0 ]; then
>         # unstash the unstashed changes
>         git stash pop -q
>         exit 1
> fi
> 
> # unstash the unstashed changes
> git stash pop -q
> exit 0
> ```

ok,I will perfect documentation next.By the way,the purpose of this project is to replace git hooks(commands) by using dart language.So the commands you want to use must change to dart language.That is what I wrote above.

**Comment by fantasy525** [comment]
@xuzhongpeng 你好，我们想在flutter项目代码提交之前用flutter analyze去检测代码规范，跟btd1337的想法类似，请问有demo吗

**Comment by xuzhongpeng** [comment]
> @xuzhongpeng 你好，我们想在flutter项目代码提交之前用flutter analyze去检测代码规范，跟btd1337的想法类似，请问有demo吗

当前库还不够完善 因为dart没有相关hooks，所以使用本库还需要额外执行一些代码，所以目前我没有维护了。

当然你说的提交代码前执行flutter analyze,其实只需要在.git/hooks/pre-commit（或者其它hooks）中加入这行命令即可
