### ISSUE TITLE
Migration to null safety

### ISSUE THREAD

**Issue by VladyslavBilomeria** [xuzhongpeng/git_hooks#11]
I noticed that this package still has not migrated to the null safety, so I created PR #10

**Comment by xuzhongpeng** [comment]
There is already a branch that does the same thing. [nullsafety](https://github.com/xuzhongpeng/git_hooks/tree/nullsafety)

**Comment by VladyslavBilomeria** [comment]
I saw that branch, but it hasn't been updated to the latest version (0.1.3 -> 0.1.6). And for some reason, I was getting a lot of errors when trying to use it.
So I created [this PR](https://github.com/xuzhongpeng/git_hooks/pull/10) for smooth migration

**Comment by weidian2021** [comment]
Thanks. I will check it soon.

**Comment by xuzhongpeng** [comment]
Thanks. I will check it soon.

**Comment by xuzhongpeng** [comment]
Done to [nullSafety](https://github.com/xuzhongpeng/git_hooks/tree/nullsafety). You can pull this branch for testing. Thank you.
