### ISSUE TITLE
Could you create the null safety version?

### ISSUE THREAD

**Issue by mengtongun** [xuzhongpeng/git_hooks#12]

**Comment by xuzhongpeng** [comment]
You can use [nullSafety branch](https://github.com/xuzhongpeng/git_hooks/tree/nullsafety) or [pub.dev git_hooks 0.1.3-nullsafety](https://pub.dev/packages/git_hooks/versions/0.1.3-nullsafety.0) instead.I will upgrade pub.dev next day.

**Comment by mengtongun** [comment]
Thank you !

**Comment by taosif7-dreamorbit** [comment]
Hi, nullsafety version is still not added on pub.dev

**Comment by xuzhongpeng** [comment]
> Hi, nullsafety version is still not added on pub.dev

Now it has pushlished to [pub.dev 1.0.0](https://pub.dev/packages/git_hooks/versions/1.0.0).
