### ISSUE TITLE
.bash_profile: No such file or directory

### ISSUE THREAD

**Issue by WiRight** [xuzhongpeng/git_hooks#19]
Not all users have bash (eg zsh)

And `source ~/.bash_profile` throw exception

**Comment by xuzhongpeng** [comment]
Fixed

**Comment by natefrechette** [comment]
will this be available through pub.dev?

**Comment by xuzhongpeng** [comment]
> will this be available through pub.dev?

done. [1.0.1](https://pub.dev/packages/git_hooks/versions/1.0.1)
