### ISSUE TITLE
null-safety?

### ISSUE THREAD

**Issue by asartalo** [xuzhongpeng/git_hooks#2]
Hi! Do you have any plans to create a null-safety release? I can help with this if you need any help although I don't really know how to properly create a tests for this.

**Comment by xuzhongpeng** [comment]
I really want to create a null-safety release. I will work on it next time. You can take a PR for me if you have some suggestions. Thank you for your attention.

**Comment by asartalo** [comment]
I would love to create a PR and I've actually did some null-safe-based changes on my fork. However, I haven't fully tested it yet and also have to clean it up because of my IDE.  How do you recommend I test the code so that it is still working as intended?

**Comment by xuzhongpeng** [comment]
You can pull a PR if your codes did not destroy the origin code. I will review and test the codes.

**Comment by xuzhongpeng** [comment]
fixed on [0.1.3-nullsafety.0](https://pub.dev/packages/git_hooks/versions/0.1.3-nullsafety.0)
