### ISSUE TITLE
git_hooks -v not working

### ISSUE THREAD

**Issue by vynguyenbao28** [xuzhongpeng/git_hooks#22]
I can't run GitHooks.init(targetPath: "bin/git_hooks.dart"); because the path could not be received. Help me

E/flutter ( 6252): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Cannot open file, path = '' (OS Error: No such file or directory, errno = 2)
E/flutter ( 6252): #0      _File.throwIfError (dart:io/file_impl.dart:629:7)
E/flutter ( 6252): #1      _File.openSync (dart:io/file_impl.dart:473:5)
E/flutter ( 6252): #2      _File.readAsBytesSync (dart:io/file_impl.dart:533:18)
E/flutter ( 6252): #3      _File.readAsStringSync (dart:io/file_impl.dart:578:18)
E/flutter ( 6252): #4      Utils.getOwnPath (package:git_hooks/utils/utils.dart:20:17)
E/flutter ( 6252): #5      GitHooks.init (package:git_hooks/runtime/git_hooks.dart:23:15)

**Comment by xuzhongpeng** [comment]
It errored out because the higher version doesn't have a `.packages` file. To fix it, look for where the `.packages` file was previously located and delete that.
