### ISSUE TITLE
When committing using terminal there is no error

### ISSUE THREAD

**Issue by vynguyenbao28** [xuzhongpeng/git_hooks#23]
If you use commit using source tree or git ide, you will get an error. But if I use the terminal to commit: git commit -m 'test format', nothing happens. This makes error tracking impossible

**Comment by xuzhongpeng** [comment]
Have you discovered the `pre-commit` file within the `.git/hooks` directory? Perhaps you could consider placing its contents there.

**Comment by vynguyenbao28** [comment]
Currently in .get/hooks there is pre-commit. Looks like I'll have to work at pre-commit, right? I saw on pub.dev that committing using the terminal will bring up messenger, but right now I don't see any signs.

**Comment by xuzhongpeng** [comment]
Which terminal did you use? Could you provide a video demonstration of the issue here?

**Comment by vynguyenbao28** [comment]
Any terminal I use causes the same situation
