### ISSUE TITLE
Issue with Git Hooks on Windows: Backslash Handling

### ISSUE THREAD

**Issue by benjilluch** [xuzhongpeng/git_hooks#25]
### Description

When running the command to create hooks on Windows:

`git_hooks create bin/git_hooks.dart`

The generated hooks in .git\hooks\ contain the following command in line 23:

`dart bin\git_hooks.dart $hookName`

On Windows, the \g in bin\git_hooks.dart is interpreted as an escape sequence, causing errors. Changing it to \\\\ fixes the issue.

### Proposed Solution

To make the setup more robust, I propose adding an OS check in the generated hooks:

- If on Windows, use \\.
- On other systems, keep the single /.

### Example Code

Below is an example of the current code generated for the hooks:

``` bash
#!/bin/sh
# !!!don"t edit this file
# xxxxxxxxxxxxxxxxxxxx
# Hook created by 
#   Version: 0.1.0
#   At: 2024-10-29 23:52:59.275156
#   See: #readme

# From
#   Homepage: #readme

hookName=`basename "$0"`
gitParams="$*"
program_exists() {
    local ret="0"
    command -v $1 >/dev/null 2>&1 || { local ret="1"; }
    if [ "$ret" -ne 0 ]; then
        return 1
    fi
    return 0
}
if program_exists dart; then
  dart bin\git_hooks.dart $hookName
  if [ "$?" -ne "0" ];then
    exit 1
  fi
else
  echo "git_hooks > $hookName"
  echo "Cannot find dart in PATH"
fi
```

### Proposed Fix

Here’s a modified version of the code that detects the operating system and adjusts the backslashes accordingly:

``` dart
var adjustedPath = path;
  if (Platform.isWindows) {
    adjustedPath = path.replaceAll(r'\', r'\\');
  }
.........
if program_exists dart; then
  dart $adjustedPath \$hookName
......
```

This change should allow the hook to function correctly across different operating systems.

Thank you for considering this compatibility improvement for Windows environments.

**Comment by xuzhongpeng** [comment]
Thank you for your advice. Fixed in 1.0.2.
