### ISSUE TITLE
Option to use `tool/git_hooks.dart` instead of `bin/git_hooks.dart`

### ISSUE THREAD

**Issue by asartalo** [xuzhongpeng/git_hooks#6]
Dart recommends that internal tools and scripts should be added under the `tool/` directory instead of `bin/` (https://dart.dev/tools/pub/package-layout#internal-tools-and-scripts).

**Use case:**

When publishing packages to pub.dev, pub will complain if there are executables under `bin/` that include dev_dependencies:

 ```
* line 4, column 1 of bin/git_hooks.dart: git_hooks is in the `dev_dependencies` section of `pubspec.yaml`. Packages used in bin/ must be declared in the `dependencies` section.
    ╷
  4 │ import 'package:git_hooks/git_hooks.dart';
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
```

**Comment by asartalo** [comment]
@xuzhongpeng worked around this by moving `bin/git_hooks.dart` to `tool/git_hooks.dart` and then manually editing the scripts under `.git/hooks/` to point to the new location.

**Comment by asartalo** [comment]
@xuzhongpeng Sorry, I just realized that you can already do this with:

```sh
pub run git_hooks create tool/git_hooks.dart
```

**Comment by xuzhongpeng** [comment]
> @xuzhongpeng Sorry, I just realized that you can already do this with:
> 
> ```shell
> pub run git_hooks create tool/git_hooks.dart
> ```

Yes. I just do it for we can use `pub global activate git_hooks` to install
