### ISSUE TITLE
[question] Using git_hooks for multiple Flutter apps in a monorepo

### ISSUE THREAD

**Issue by joshuadeguzman** [xuzhongpeng/git_hooks#9]
### Description

The `.git` configuration of the project is in the root of the monorepo, which is not a Flutter app (no pubspec.yaml). This monorepo contains different Flutter apps talking relatively importing each other. I'm interested to know if there are available workarounds getting `git_hooks` to work subdirectories of Flutter apps in a monorepo. 

### Issue

1. Creating `git_hooks` within one of the Flutter subdirectory

```
$ git_hooks create bin/git_hooks.dart    
create files...                        /Invalid argument(s): .git is not exists in your project
```

2. Creating `git_hooks` in the root (obviously won't work)

```
$ git_hooks create bin/git_hooks.dart    

... app/pubspec.yaml' (OS Error: No such file or directory, errno = 2)
```

### Attachments

monorepo
- flutter_app_1
- flutter_app_2
- .git

Thanks for the great work on this tool

**Comment by joshuadeguzman** [comment]
A workaround that I found is to manually set the execution of the commands going through each directory in the `pre-commit` script under `.git/hooks`.

**Comment by xuzhongpeng** [comment]
This is really a problem. I will do something for optimizing.
